// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzFIwmjAJEJEuAzX573Z8Bc9pafpMV8mU',
    appId: '1:134085688768:web:3420efe638ccb8fd6d1c25',
    messagingSenderId: '134085688768',
    projectId: 'meliusfocus',
    authDomain: 'meliusfocus.firebaseapp.com',
    storageBucket: 'meliusfocus.firebasestorage.app',
    measurementId: 'G-N0W824E0RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4c2R9D9qp6jfaEGt7jRfwavTRtPXaUa8',
    appId: '1:134085688768:android:80532047ae8d80bf6d1c25',
    messagingSenderId: '134085688768',
    projectId: 'meliusfocus',
    storageBucket: 'meliusfocus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrZnV7RxezNYHP_Nhc98j2Y8qE3aIvcs',
    appId: '1:134085688768:ios:a51772b345b3db496d1c25',
    messagingSenderId: '134085688768',
    projectId: 'meliusfocus',
    storageBucket: 'meliusfocus.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXrZnV7RxezNYHP_Nhc98j2Y8qE3aIvcs',
    appId: '1:134085688768:ios:a51772b345b3db496d1c25',
    messagingSenderId: '134085688768',
    projectId: 'meliusfocus',
    storageBucket: 'meliusfocus.firebasestorage.app',
    iosBundleId: 'com.example.cs310Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzFIwmjAJEJEuAzX573Z8Bc9pafpMV8mU',
    appId: '1:134085688768:web:05b86508ef5d43556d1c25',
    messagingSenderId: '134085688768',
    projectId: 'meliusfocus',
    authDomain: 'meliusfocus.firebaseapp.com',
    storageBucket: 'meliusfocus.firebasestorage.app',
    measurementId: 'G-NPP6S0668S',
  );
}
